### ISSUE TITLE
manjaro jdk11版本打开提示错误

### ISSUE THREAD

**Issue by Axianke** [WankkoRee/BurpLoaderKeygenCnF#7]
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd
Exception in thread "main" java.lang.NullPointerException
at cn.wankkoree.burploaderkeygencnf.KeygenForm.GetCMD(KeygenForm.java:90)
at cn.wankkoree.burploaderkeygencnf.KeygenForm.main(KeygenForm.java:188)

**Comment by WankkoRee** [comment]
请尝试更换 jre 版本，推荐使用 jre9 ~ jre14 。
